exercises/crud/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # BEGIN
  resources :tasks
  # END
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

exercises/crud/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

exercises/crud/app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :name, :status, :creator, presence: true
end

exercises/crud/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

exercises/crud/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

exercises/crud/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :find_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.order(created_at: :desc)
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :status, :creator, :performer, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

exercises/crud/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

exercises/crud/app/helpers/task_helper.rb
# frozen_string_literal: true

module TaskHelper
end

exercises/crud/app/views/home/index.html.erb
<h1>Home#index</h1>

exercises/crud/app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <div>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div>
    <%= f.label :creator %>
    <%= f.text_field :creator %>
  </div>

  <div>
    <%= f.label :performer %>
    <%= f.text_field :performer %>
  </div>

  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>

  <%= f.submit %>
<% end %>

exercises/crud/app/views/tasks/edit.html.erb
<h2>Edit <%= @task.name %></h2>

<%= render 'form' %>

exercises/crud/app/views/tasks/index.html.erb
<h2>Tasks</h2>
<div>
<% @tasks.each do |task| %>
  <h3><%= link_to task.name, task_path(task) %></h3>
<% end %>
</div>

exercises/crud/app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= render 'form' %>

exercises/crud/app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<table>
  <tr>
    <td>Creator</td>
    <td>Performer</td>
    <td>Status</td>
    <td>Completed</td>
  </tr>
 <tr>
    <td><%= @task.creator %></td>
    <td><%= @task.performer %></td>
    <td><%= @task.status %></td>
    <td><%= t @task.completed? %></td>
  </tr>
</table>
<p><%= @task.description %></p>
<div><%= link_to 'Edit', edit_task_path(@task) %></div>
<div><%= link_to 'Destroy', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %></div>