exercises/quality/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # BEGIN
  resources :bulletins, only: %i[index show]
  # END
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

exercises/quality/app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
end

exercises/quality/app/controllers/bulletins_controller.rb
# frozen_string_literal: true

class BulletinsController < ApplicationController
  # BEGIN
  def index
    @bulletins = Bulletin.all
  end

  def show
    @bulletin = Bulletin.find(params[:id])
  end
  # END
end

exercises/quality/app/helpers/bulletins_helper.rb
# frozen_string_literal: true

module BulletinsHelper
end

exercises/quality/app/views/bulletins/index.html.erb
<h1>Bulletins</h1>
<%# BEGIN %>
<% @bulletins.each do |bulletin| %>
  <h2><%= link_to bulletin.title, bulletin_path(bulletin) %></h2>
<% end %>
<%# END %>

exercises/quality/app/views/bulletins/show.html.erb
<%# BEGIN %>
<h2><%= @bulletin.title %></h2>
<p><%= @bulletin.body %></p>
<%# END %>

exercises/quality/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quality</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to 'Bulletins', bulletins_path %></li>
  </ul>
    <%= yield %>
  </body>
</html>